### ISSUE TITLE
Getting "Uncaught TypeError: Cannot read properties of undefined (reading 'buffer')"

### ISSUE THREAD

**Issue by takanuva15** [gmariani/minerva#112]
I was trying to edit the ByteArray within "SDAT" of this sol file, but it won't save after doing any edit to the ByteArray:
[RoadZ2.sol.txt](https://github.com/user-attachments/files/17514849/RoadZ2.sol.txt)
(GitHub does not allow me to upload SOL files, so please remove the `.txt` extension before uploading the sol file)

Here's what it shows in the browser console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'buffer')
    at ByteArray.writeBytes (ByteArray.20230424_1682375014103.js:1:1244)
    at AMF3.writeByteArray (AMF3.20230424_1682375014103.js:1:10166)
    at AMF3.writeData (AMF3.20230424_1682375014103.js:1:3650)
    at onmessage (SOLWriterWorker.20230424_1682375014103.js:1:559)
```

Steps:
- Upload the sol file (I'm using Chrome)
- Click "SDAT", select "ZLIB", and click "Uncompress"
- Edit any reasonable byte, such as copying a byte on the 1st row to change "unlock" to "unlokk"
- Save the file
- A popup will show with the error

**Comment by gmariani** [comment]
Was able to reproduce the error, I'll see when I have some free time to dig into this. 
Noting the error is different on Firefox:
```
08:29:14.024 TypeError: t._dataview is undefined ByteArray.20230424_1682375014103.js:1:1232
    writeBytes https://mariani.life/projects/minerva/js/lib/ByteArray.20230424_1682375014103.js:1
    writeByteArray https://mariani.life/projects/minerva/js/lib/AMF3.20230424_1682375014103.js:1
    writeData https://mariani.life/projects/minerva/js/lib/AMF3.20230424_1682375014103.js:1
    onmessage https://mariani.life/projects/minerva/js/parsers/SOLWriterWorker.20230424_1682375014103.js:1
```
