### ISSUE TITLE
Exports "undefined"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gmariani/minerva#58]
```
In Chrome 40.0.2214.91 m, using the attached file, when I attempt to Export I 
get a text file that contains only "undefined", and the following exception is 
thrown in the console (doubtful it helps):

TypeError: Cannot read property 'length' of undefined
    at c (http://cdn.coursevector.com/minerva/4.1.1/js/main.min.js:274:409)
    at c (http://cdn.coursevector.com/minerva/4.1.1/js/main.min.js:275:34)
    at c (http://cdn.coursevector.com/minerva/4.1.1/js/main.min.js:274:481)
    at HTMLAnchorElement.<anonymous> (http://cdn.coursevector.com/minerva/4.1.1/js/main.min.js:303:475)
    at HTMLAnchorElement.n.event.dispatch (http://cdn.coursevector.com/minerva/4.1.1/js/main.min.js:3:6404)
    at HTMLAnchorElement.n.event.add.r.handle (http://cdn.coursevector.com/minerva/4.1.1/js/main.min.js:3:3179)
```

Original issue reported on code.google.com by `jdkne...@gmail.com` on 24 Jan 2015 at 5:35

Attachments:
- [00000001.sol](https://storage.googleapis.com/google-code-attachments/cv-minerva/issue-58/comment-0/00000001.sol)

**Comment by gmariani** [comment]
Tested again on Chrome v63 without issue. Re-open if this is still a problem.
